### ISSUE TITLE
Please ensure the new updates do not break the page

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#31]
Currently the development branch is broken 
https://github.com/enanomapper/data.enanomapper.net/tree/development

````
Uncaught TypeError: settings.SpyManager is not a constructor
    at A.jT.AutocompleteWidget (file:///.../data.enanomapper.net/lib/jToxKit/www/jtox-kit.widgets.js:453:21)
    at file:///../data.enanomapper.net/lib/asSys/as-sys.js:55:13
````

**Comment by vedina** [comment]
works now
